name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          dot -V
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir -p staging/generated-diagrams && cp target/*.jar staging && cp -r target/generated-diagrams/* staging/generated-diagrams/
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
      - name: Detect PUML changes
        id: puml
        run: |
          changed=false
          
          # tracked files
          if ! git diff --quiet -- docs/generated-diagrams; then
            changed=true
          fi

          # untracked files 
          if [ "$changed" = false ] && \
            [ -n "$(git ls-files --others --exclude-standard -- docs/generated-diagrams)" ]; then
            changed=true
          fi

          echo "changed found: $changed"
          echo "changed=$changed" >> "$GITHUB_OUTPUT"
      - name: Commit generated diagrams
        if: >
          github.event_name == 'pull_request' &&
          steps.puml.outputs.changed == 'true' &&
          github.event.pull_request.head.repo.full_name == github.repository
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/generated-diagrams'
          message: 'update generated UML diagrams'
